modLoader="javafml"
loaderVersion="[30,)"
[[mods]]
modId="adlib"
version="${file.jarVersion}"
displayName="ADLib"
authors="AlasDiablo"
description='''
A minecraft libary for AlasDiablo's Mods
'''
[[dependencies.adlib]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.adlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="BOTH"
